name: Build & Deploy Digital Garden

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: digital-garden

      - uses: actions/checkout@v4
        with:
          path: quartz
          repository: jackyzha0/quartz

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: |
          cp -av digital-garden/. quartz/
          cd quartz
          npm i
          npx quartz build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/public/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write
      actions: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
